version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    reviewers:
      - bitpatty
    labels:
      - dependencies
