name: RAB_MySQL-5.7

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.102' ]
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          # The port of host
          host port: 3306
          # The port of container
          container port: 3306
          mysql version: '5.7'
          mysql root password: 'root'
          mysql database: 'rab_t1'
          mysql user: 'devel'
          mysql password: 'devel'
      - name: Checkout
        uses: actions/checkout@v1  
      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Run tests
        run: dotnet test --verbosity normal
